#!/bin/bash
# The first argument is the date the item is due.
# 
# Is the first argument a command?  Commands so far are ls
if [ $# == 0 ]
then
    set -- ls
fi
if [ "$1" == "ls" ]
then
    FILES="todo_dir/*"
    for f in $FILES
    do
        fn=$(basename $f)
        echo -n $fn ">> "
        head -1 $f
    done
    exit
fi
dd=$(date +%Y-%m-%d_%R --date="$1")
if [ $? == 0 ]
then
    echo $dd
else
    echo "Didn't understand the date"
    exit 1
fi
# Now collect the input
task=$(cat)
# Pick out the next serial number and increment it.
serial=$(cat .todo_number)
(( serial++ ))
fnx=$(echo -n 0000$serial | tail -c 3)
dd=$dd#$fnx
# and save into file named after the given date in private directory
echo "$task" >"todo_dir/$dd"
echo $serial >.todo_number
