#!/bin/bash
# 
# Set dir to the directory where everything is kept
# This directory must contain a .todo_number file containing the next number to be issued.
dir=~/ToDo/SRC/todo_dir

today=$(date +%Y-%m-%d)
# Is the first argument a command?  Commands so far are ls
if [ $# == 0 ]
then
    set -- ls
fi
if [ "$1" == "ls" ]
then
    FILES="$dir/*"
    for f in $FILES
    do
        fn=$(basename $f)
        echo -n $fn
        tn=${fn: 0: 10}
        if [[ $tn < $today ]]
        then
            echo -n ' << '
        elif [[ $tn == $today ]]
        then
            echo -n ' == '
        else
            echo -n ' >> '
        fi
        head -1 $f
    done
    exit
elif [ "$1" == "cat" ]
then
    cat $dir/*#$2
    exit $?
elif [ "$1" == "vi" ]
then
    vi $dir/*#$2
    exit $?
elif [ "$1" == "rm" ]
then
    rm $dir/*#$2
    exit $?
fi

# The first argument is the date the item is due.
dd=$(date +%Y-%m-%d_%R --date="$1")
if [ $? == 0 ]
then
    echo $dd
else
    echo "Didn't understand the date"
    exit 1
fi
# Now collect the input
task=$(cat)
# Pick out the next serial number and increment it.
serial=$(cat $dir/.todo_number)
(( serial++ ))
fnx=000$serial
fnx=${fnx: -3: 3}
dd=$dd#$fnx
# and save into file named after the given date in private directory
echo "$task" >"$dir/$dd"
echo $serial >$dir/.todo_number
